project:
  type: website

website:
  title: "Cd /Users/vark/Desktop/student-exam-performances"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



